[project]
name = "learningforoptimizing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["torch>=2.4.0", "numpy>=2.1.0", "python-dotenv"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
